- name: "Test playbook run"
  hosts: all
  
  tasks:
      copy:
      - name: "Копируем"
        ansible.builtin.copy:
          src: ./index.html
          dest: /opt/dockersite
          mode: '0775'
      - name: "Debug"
        ansible.builtin.debug:
          msg: "Получилось"
